### PR TITLE
adaptived: Add initial version

### PR DESCRIPTION
**Pull request by drakenclimber**
Add adaptived to the adaptivemm github repo.

~Note that the github action to run `make distcheck` is failing.  It's unable to create a systemd slice - e.g. `.........Error: Can't create cgroup: /sys/fs/cgroup/sudo1005.slice`, but these tests work when run as part of `make check`.   We'll need to solve it, but it's obviously a github actions issue, so I feel comfortable merging it as is and resolving that later.~        Fixed in forced push eacdfbc

### CODE REVIEW

**Comment by drakenclimber** [comment]
I fixed the failing `make distcheck` github action by bumping it to run on Ubuntu latest (which is cgroup v2).  We'll need to sort out our vision for cgroup v1 testing, but now all of the tests pass :) :)

**Comment by drakenclimber** [comment]
Here's a link to the passing tests (since they aren't yet incorporated into pull requests for this repo):
https://github.com/drakenclimber/adaptivemm/actions/runs/11469496899/job/31916839835

**Comment by drakenclimber** [comment]
Code coverage is claiming 23%, but when I run things locally I'm seeing 70%+.  Looks like we aren't getting the numbers properly reported to coveralls yet.
https://coveralls.io/github/drakenclimber/adaptivemm

**Comment by drakenclimber** [comment]
Commit 5c8bcf5 is a non-functional change.  I added systemd to the list of requirements in the THIRD_PARTY_LICENSES.txt file

**Comment by drakenclimber** [comment]
Commit 06e9cee fixes the code coverage numbers, and they're now reporting 70.7% :+1: 

https://coveralls.io/builds/70502291

**Comment by sidkumar99** [comment]
Reviewed-by: Sidhartha Kumar <sidhartha.kumar@oracle.com>

**Pull request merged**
